name: PR Build Validation (Windows)

on:
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: Build for Windows
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot - Export Templates
        uses: chickensoft-games/setup-godot@v2
        with:
          version: '4.3.0'
          include-templates: true
          path: godot
          downloads-path: downloads
          bin-path: bin
          use-dotnet: true
          cache: true

      - name: Install Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb
          
      - name: Criar Diretório de Build
        run: mkdir -p build/windows
      
      - name: Import Godot Resources
        run: xvfb-run ${{ steps.setup_godot.outputs.godot-path }} --headless --import

      - name: Run Unit Tests and Calculate Coverage
        run: xvfb-run ${{ steps.setup_godot.outputs.godot-path }} --headless -s addons/gut/gut_cmdln.gd -gdir=res://tests -gprefix=test_ -gcoverage=true -gcov_dir=res://scripts,res://game_assets/classes

      - name: Export Game (Windows Debug Build for PR)
        id: export_game
        run: |
          echo "Tentando exportar o jogo..."
          set +e
          xvfb-run ${{ steps.setup_godot.outputs.godot-path }} --headless --verbose --export-debug "Windows Desktop" "build/windows/TicketToClass_Dev.exe" 2>&1 | tee godot_export_log.txt
          GODOT_EXIT_CODE=$?
          set -e

          echo "Processo finalizado com código de saída: $GODOT_EXIT_CODE"
          echo "--- Godot Export Log ---"
          cat godot_export_log.txt
          echo "--- End of Godot Export Log ---"
          
          if grep -q -E "SCRIPT ERROR:|ERROR: Failed to load script" godot_export_log.txt; then
            echo "::error::Script errors found during Godot export. Failing build."
            exit 1
          elif [ $GODOT_EXIT_CODE -ne 0 ]; then
            echo "::error::Godot export command failed with exit code $GODOT_EXIT_CODE. Failing build."
            exit 1
          fi
          echo "Godot export completed successfully without critical script errors."

      - name: Arquiva Windows Build Output
        shell: bash
        run: |
          cd build/windows
          EXECUTABLE_NAME="TicketToClass_Dev.exe"
          PCK_NAME="${EXECUTABLE_NAME%.exe}.pck"
          ARCHIVE_NAME="TicketToClass_Dev_Windows.zip"

          if [ -f "$EXECUTABLE_NAME" ] && [ -f "$PCK_NAME" ]; then
            zip "$ARCHIVE_NAME" "$EXECUTABLE_NAME" "$PCK_NAME"
          elif [ -f "$EXECUTABLE_NAME" ]; then
            zip "$ARCHIVE_NAME" "$EXECUTABLE_NAME"
          else
            echo "Executável não encontrado para arquivar."
            exit 1
          fi
          mv "$ARCHIVE_NAME" ../

      - name: Upload de Artefato - Dev Build (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: dev-build-windows
          path: |
            build/TicketToClass_Dev_Windows.zip
          if-no-files-found: error
          retention-days: 7
